name: Checks

on: push

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Run tests
        run: mise r test
